# Generated by Django 2.2.2 on 2019-10-20 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ds_exchange.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=ds_exchange.models.now_slug, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('from_currency', models.CharField(default='jpy', max_length=3)),
                ('to_currency', models.CharField(default='rmb', max_length=3)),
                ('due_at', models.DateTimeField(default=datetime.datetime(2019, 10, 23, 20, 56, 16, 103231))),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=10)),
                ('privacy', models.CharField(default='public', max_length=10)),
                ('send_notification', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, default='...', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ds_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_place_order', 'Can place order'), ('can_edit_order', 'Can edit order')),
            },
        ),
    ]
