# Generated by Django 2.2.2 on 2019-10-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsorder',
            name='bonuspoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 10, 48, 53, 365337)),
        ),
    ]
