# Generated by Django 2.2.2 on 2019-10-21 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0002_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 12, 19, 46, 606929)),
        ),
    ]
