# Generated by Django 2.2.2 on 2019-10-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0003_auto_20191022_1117'),
        ('ds_exchange', '0003_auto_20191021_1219'),
    ]

    operations = [
    ]
