# Generated by Django 2.2.2 on 2019-10-22 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0003_auto_20191022_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 21, 0, 39, 128788)),
        ),
    ]
