# Generated by Django 2.2.2 on 2019-10-22 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0004_auto_20191022_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 21, 36, 54, 590552)),
        ),
    ]
