# Generated by Django 2.2.2 on 2019-10-25 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0008_auto_20191025_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 23, 2, 6, 516630)),
        ),
    ]
