# Generated by Django 2.2.2 on 2019-10-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0006_merge_20191022_2145'),
        ('ds_exchange', '0010_auto_20191025_2305'),
    ]

    operations = [
    ]
