# Generated by Django 2.2.2 on 2019-11-07 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0011_auto_20191027_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 22, 29, 5, 148792)),
        ),
    ]
