# Generated by Django 2.2.2 on 2019-11-07 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0012_auto_20191107_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 22, 30, 33, 823327)),
        ),
    ]
