# Generated by Django 2.2.2 on 2019-11-18 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0015_merge_20191112_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 21, 15, 15, 315837)),
        ),
    ]
