# Generated by Django 2.2.2 on 2019-11-18 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0016_auto_20191118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 21, 21, 21, 124370)),
        ),
    ]
