# Generated by Django 2.2.2 on 2019-11-19 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0018_auto_20191118_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 20, 24, 4, 39929)),
        ),
    ]
