# Generated by Django 2.2.2 on 2019-11-19 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0019_auto_20191119_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 20, 33, 34, 376408)),
        ),
    ]
