# Generated by Django 2.2.2 on 2019-11-19 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0022_auto_20191119_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 22, 22, 13, 32, 137421)),
        ),
    ]
