# Generated by Django 2.2.2 on 2019-11-21 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0026_auto_20191120_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 7, 28, 32, 709807)),
        ),
    ]
