# Generated by Django 2.2.2 on 2019-11-28 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0044_auto_20191124_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 22, 58, 29, 278859)),
        ),
    ]
