# Generated by Django 2.2.2 on 2019-11-28 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0045_auto_20191128_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 23, 34, 50, 311443)),
        ),
    ]
