# Generated by Django 2.2.2 on 2019-11-30 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0046_auto_20191128_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 17, 50, 34, 306173)),
        ),
    ]
