# Generated by Django 2.2.2 on 2019-11-30 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0048_auto_20191130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 18, 27, 38, 378808)),
        ),
    ]
