# Generated by Django 2.2.2 on 2019-12-08 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0049_auto_20191130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 18, 31, 6, 559332)),
        ),
    ]
