# Generated by Django 2.2.2 on 2019-12-12 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0051_auto_20191212_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 20, 26, 1, 722084)),
        ),
    ]
