# Generated by Django 2.2.2 on 2019-12-17 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0052_auto_20191212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 23, 12, 50, 228301)),
        ),
    ]
