# Generated by Django 2.2.2 on 2019-12-18 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0054_auto_20191217_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 23, 11, 47, 6682)),
        ),
    ]
