# Generated by Django 2.2.2 on 2019-12-22 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0057_auto_20191222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 17, 8, 40, 329892)),
        ),
    ]
