# Generated by Django 2.2.2 on 2019-12-24 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0058_auto_20191222_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 23, 31, 47, 845792)),
        ),
    ]
