# Generated by Django 2.2.2 on 2019-12-24 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0060_auto_20191224_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 23, 37, 4, 14526)),
        ),
    ]
