# Generated by Django 2.2.2 on 2019-12-28 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0062_auto_20191225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 11, 37, 13, 114876)),
        ),
    ]
