# Generated by Django 2.2.2 on 2020-01-08 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0065_auto_20200108_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 48, 44, 507740)),
        ),
    ]
