# Generated by Django 2.2.2 on 2020-01-08 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_exchange', '0066_auto_20200108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsorder',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 18, 21, 33, 804454)),
        ),
    ]
