# Generated by Django 2.2.2 on 2019-12-24 23:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rentalhouse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery_shop', '0021_snsurl'),
        ('shoppingcart', '0007_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A', max_length=10)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rental_productranks',
            },
        ),
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=rentalhouse.models.now_slug, null=True)),
                ('sn', models.CharField(default='serialno', max_length=50)),
                ('condition', models.CharField(blank=True, default='new', max_length=20)),
                ('avaliable', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalproducts', to='lottery_shop.Product')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankproducts', to='rentalhouse.ProductRank')),
            ],
            options={
                'verbose_name': 'RentalProduct',
                'db_table': 'rental_products',
            },
        ),
        migrations.CreateModel(
            name='RentalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=rentalhouse.models.now_slug, null=True)),
                ('start_at', models.DateTimeField(default=datetime.datetime(2019, 12, 24, 23, 31, 47, 882434))),
                ('end_at', models.DateTimeField(default=datetime.datetime(2019, 12, 24, 23, 31, 47, 882522))),
                ('days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('booked', 'booked'), ('toCustomer', 'toCustomer'), ('fromCustomer', 'fromCustomer'), ('inTrouble', 'inTrouble'), ('completed', 'completed')], default='booked', max_length=20)),
                ('memo', models.TextField(default='memo', max_length=1024)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalproducts', to='rentalhouse.RentalProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RentalHistory',
                'db_table': 'rental_histories',
            },
        ),
    ]
