# Generated by Django 2.2.2 on 2019-12-24 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 23, 34, 32, 157384)),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 23, 34, 32, 157297)),
        ),
    ]
