# Generated by Django 2.2.2 on 2019-12-24 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhouse', '0002_auto_20191224_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
