# Generated by Django 2.2.2 on 2019-12-28 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhouse', '0003_auto_20191224_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='rentalhouse.RentalProduct'),
        ),
        migrations.AlterField(
            model_name='rentalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myhistories', to=settings.AUTH_USER_MODEL),
        ),
    ]
