# Generated by Django 2.2.2 on 2019-12-29 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalhouse', '0004_auto_20191228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myrentalhistories', to=settings.AUTH_USER_MODEL),
        ),
    ]
