version: '3.5'
services:
  # portainer:
  #   image: portainer/portainer
  #   command: -H unix:///var/run/docker.sock
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

        
  pgadmin4:
    image: dpage/pgadmin4:4.14
    container_name: pgadmin4
    ports:
      - 6080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: Hisshghu3500
    hostname: pgadmin4
    restart: always
    networks:
      - exrate_network

  redis:
    container_name: redis
    restart: always
    tty: true
    build:
      context: ./system/redis
    environment:
      TZ: Asia/Tokyo
    # ports:
    #   - 16379:6379
    volumes:
      - ./system/redis/redis_data:/var/redis
      - ./conf/6379.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes
    networks:
      - exrate_network

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - ./system/pgdata:/var/lib/postgresql/data/
    # ports:
    #   - 15432:5432
    networks:
      - exrate_network

  rabbitmq:
    container_name: rabbitmq
    image:  rabbitmq:3.7.3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: my_vhost
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    networks:
      - exrate_network


  web:
    image: lionhu/docker_vue:v7
    container_name: web_nginx
    # build: .
    # ports:
      # - "80:80"
      # - "8081:8081"
      # - "8001:8001"
      # - "2443:443"
    volumes:
      - ./system/nginx/nginx_base_django.conf:/etc/nginx/nginx.conf
      - ./system/nginx/nginx_django.conf:/etc/nginx/conf.d/nginx_django.conf
      - ./system/logs:/var/log/webapplications
      - ./project:/django_project
    depends_on:
      - redis
      - postgres
      - rabbitmq
    networks:
      - exrate_network
      - proxy-network
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=www.exrate.world


  worker:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile_worker
    image: lionhu/exrate_misawa_worker:v0
    container_name: django_worker
    restart: always
    tty: true
    volumes:
      - ./project:/django_project
      - ./system/logs:/var/log/webapplications
    links:
      - rabbitmq
      - postgres
      - redis
    networks:
      - exrate_network


volumes:
  portainer_data:


networks:
  proxy-network:
    name: proxy-network
  exrate_network:
    name: exrate_network