version: "3.5"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - 2080:80
      # - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      proxy-network:
        ipv4_address: 172.18.0.2


networks:
  proxy-network:
    ipam:
       config:
       - subnet: 172.18.0.0/16