FROM python:3.7.3
LABEL maintainer Lionhu
ENV PYTHONUNBUFFERED 1
RUN mkdir /django_project
WORKDIR /django_project

RUN apt-get update && apt-get install -y  supervisor vim

RUN mkdir -p /var/log/webapplications


RUN mkdir -p /etc/supervisor/logs/
COPY /system/nginx/supervisord_worker.conf /etc/supervisor/conf.d/supervisord.conf


COPY /project/requirements.txt /django_project/requirements.txt
RUN pip install -r requirements.txt


CMD ["/usr/bin/supervisord", "-c","/etc/supervisor/conf.d/supervisord.conf"]
