version: '3.5'
services:
  # portainer:
  #   image: portainer/portainer
  #   command: -H unix:///var/run/docker.sock
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  pgadmin4:
    image: dpage/pgadmin4:4.14
    container_name: pgadmin4
    ports:
      - 6080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: Hisshghu3500
    hostname: pgadmin4
    restart: always
    networks:
     extnetwork:
        ipv4_address: 172.19.0.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=Hisshghu3500
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - /sessions
    networks:
     extnetwork:
        ipv4_address: 172.19.0.9

  php:
    # image: lionhu/php73:v0
    container_name: php
    build: ./system/php
    volumes:
      - ./misawa:/var/www/html
      - ./system/logs:/var/log/webapplications
    networks:
     extnetwork:
        ipv4_address: 172.19.0.8

  mysql:
    # image: mysql:5.7
    image: lionhu/mysql57:v0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hisshghu3500
      MYSQL_DATABASE: misawa2020
      MYSQL_USER: root
      MYSQL_PASSWORD: Hisshghu3500
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./system/mysql/data:/var/lib/mysql
    - ./system/mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./system/mysql/sql:/docker-entrypoint-initdb.d
    ports:
    - 3308:3306
    networks:
     extnetwork:
        ipv4_address: 172.19.0.7


  redis:
    container_name: redis
    restart: always
    tty: true
    build:
      context: ./system/redis
    environment:
      TZ: Asia/Tokyo
    ports:
      - 16379:6379
    volumes:
      - ./system/redis/redis_data:/var/redis
    command: redis-server --appendonly yes
    networks:
     extnetwork:
        ipv4_address: 172.19.0.6

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - ./system/pgdata:/var/lib/postgresql/data/
    ports:
      - 15432:5432
    networks:
     extnetwork:
        ipv4_address: 172.19.0.2

  rabbitmq:
    container_name: rabbitmq
    image:  rabbitmq:3.7.3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: celery
      RABBITMQ_DEFAULT_PASS: password123
      RABBITMQ_DEFAULT_VHOST: my_vhost
    ports:
      - 5672:5672
      - 15672:15672
    networks:
     extnetwork:
        ipv4_address: 172.19.0.3


  web:
    image: lionhu/docker_vue:v7
    container_name: web_nginx
    # build: .
    ports:
      - "2080:80"
      - "8081:8081"
      - "8001:8001"
      # - "2443:443"
    volumes:
      - ./system/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./system/nginx/nginx_laravel.conf:/etc/nginx/conf.d/nginx_laravel.conf
      - ./system/nginx/nginx_django.conf:/etc/nginx/conf.d/nginx_django.conf
      # - ./system/nginx/certs:/usr/local/nginx/certs
      - ./system/logs:/var/log/webapplications
      - ./misawa:/var/www/html
      - ./project:/django_project
    links: 
      - redis
      - postgres
      - rabbitmq
    depends_on:
      - php
    networks:
     extnetwork:
        ipv4_address: 172.19.0.4


  worker:
    build: 
      context: .
      dockerfile: Dockerfile_worker
    container_name: django_worker
    restart: always
    tty: true
    volumes:
      - ./project:/django_project
      - ./system/logs:/var/log/webapplications
    links:
      - rabbitmq
      - postgres
      - redis
    networks:
     extnetwork:
        ipv4_address: 172.19.0.5


volumes:
  portainer_data:


networks:
  extnetwork:
      ipam:
         config:
         - subnet: 172.19.0.0/16