# Generated by Django 2.2.2 on 2019-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hui_in', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('hui_out', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('chao_in', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('chao_out', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('zhesuan', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('mid_price', models.DecimalField(blank=True, decimal_places=4, default=6.0, max_digits=10, null=True)),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bankrates',
            },
        ),
    ]
