# Generated by Django 2.2.2 on 2019-07-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankrate',
            name='mid_price',
        ),
        migrations.RemoveField(
            model_name='bankrate',
            name='zhesuan',
        ),
    ]
