# Generated by Django 2.2.2 on 2019-08-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exrate', '0002_auto_20190721_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('02a99f2b-0046-4dbe-920e-29459d77a371'), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='rmb', max_length=5)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BonusDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('5799c7c8-a08c-43f0-b9a7-7f07f67094d0'), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='rmb', max_length=5)),
                ('amount', models.IntegerField(default=0)),
                ('fromType', models.CharField(blank=True, max_length=20, null=True)),
                ('fromOjbectID', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=100)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exrate.Bonus')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
