# Generated by Django 2.2.2 on 2019-08-03 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0003_bonus_bonusdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='amount',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('965baf56-582e-47c0-b65c-9c7b18e5236e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ab9fed20-db0b-4c34-9557-8527621c7c48'), null=True),
        ),
    ]
