# Generated by Django 2.2.2 on 2019-08-03 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0004_auto_20190803_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonusdetail',
            old_name='fromOjbectID',
            new_name='fromObjectID',
        ),
        migrations.AddField(
            model_name='bonus',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b9a36c8e-f370-4d60-ab69-65cecb98545d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('acbf7909-d290-41a5-a26e-15957fb6fa74'), null=True),
        ),
    ]
