# Generated by Django 2.2.2 on 2019-08-03 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0005_auto_20190803_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('854e686d-28cc-4ec0-94f7-d74d4853adfe'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5881f7bd-ea04-4e2c-a401-a5aed143c376'), null=True),
        ),
    ]
