# Generated by Django 2.2.2 on 2019-08-03 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0006_auto_20190803_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('434ec8fa-5221-4c19-9be8-d3f5d9ff6e98'), null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('558bddb2-2ac7-46b0-a2d0-2e69551e1d1f'), null=True),
        ),
    ]
