# Generated by Django 2.2.2 on 2019-08-09 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0007_auto_20190803_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bc4b3061-3207-463c-88df-6aa563716650'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9795b6dd-2124-441c-9dd5-3fae56e0b981'), null=True),
        ),
    ]
