# Generated by Django 2.2.2 on 2019-08-16 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0008_auto_20190809_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8897fa96-099f-4887-8a61-298b1c8be34f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('528eaa05-6386-4091-bd91-7c45eccd6191'), null=True),
        ),
    ]
