# Generated by Django 2.2.2 on 2019-08-17 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0009_auto_20190816_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9202eaca-e836-4364-b226-7adc004d38f0'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e09826f7-05f0-4519-9fbb-b775dd0303e3'), null=True),
        ),
    ]
