# Generated by Django 2.2.2 on 2019-08-18 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0010_auto_20190817_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4ff8d902-44ea-475f-9dc6-53021a72e815'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6bb9bcb8-ba17-4b32-8d85-8c98392df907'), null=True),
        ),
    ]
