# Generated by Django 2.2.2 on 2019-08-25 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0011_auto_20190818_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4de6efa0-ebcb-4c85-a9f4-64f28bef4703'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a843aabe-4697-4fef-b1a1-5b8812be70ce'), null=True),
        ),
    ]
