# Generated by Django 2.2.2 on 2019-08-25 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0012_auto_20190825_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ca533ce5-c354-478c-934d-2767cef62ace'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a86ceb9e-a090-42ec-8fb5-e938711b8f8a'), null=True),
        ),
    ]
