# Generated by Django 2.2.2 on 2019-08-25 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0013_auto_20190825_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9f520e37-8dfc-43e7-a3a3-fa38b488065d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8fdea7b2-ed9b-4e9e-af51-376c62b8886f'), null=True),
        ),
    ]
