# Generated by Django 2.2.2 on 2019-08-26 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0014_auto_20190825_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('62c172b2-2aa1-44c5-8d49-98467cabad69'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('674a8ebd-469c-47b1-982f-fd6affdd7bc9'), null=True),
        ),
    ]
