# Generated by Django 2.2.2 on 2019-08-26 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0015_auto_20190826_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3514cdc8-1be5-4d9d-85ee-a1b058d0611d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6214ac2c-5d83-4b5d-971c-cbaa71789100'), null=True),
        ),
    ]
