# Generated by Django 2.2.2 on 2019-08-26 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0016_auto_20190826_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('47066736-af91-4a2c-8409-2d9df6a09f87'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6ed3e931-f041-45f3-ac84-7dba882858fc'), null=True),
        ),
    ]
