# Generated by Django 2.2.2 on 2019-08-26 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0017_auto_20190826_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('551a9d3a-52c5-4e69-8a7b-76d269496670'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5d0af17b-3d75-4f75-9089-7525c9d4c7de'), null=True),
        ),
    ]
