# Generated by Django 2.2.2 on 2019-08-31 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0018_auto_20190826_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('45c959b9-c943-4a3b-ab8c-5b4554dd4fcf'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0ff40f36-e465-4d30-9368-ba5d65c57e2c'), null=True),
        ),
    ]
