# Generated by Django 2.2.2 on 2019-09-04 20:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0019_auto_20190831_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ddc611fb-f549-4bcb-853e-837d48ca1aae'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c2d91292-487e-44b5-a44c-3dc269cf712a'), null=True),
        ),
    ]
