# Generated by Django 2.2.2 on 2019-09-10 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0020_auto_20190904_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b20a2ae7-e9a9-49cf-b7e8-311b154c8035'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f7dc4472-d133-4c1e-865a-c1df6848614b'), null=True),
        ),
    ]
