# Generated by Django 2.2.2 on 2019-09-11 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0021_auto_20190910_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('88bde40f-26a5-4a39-898f-f6cfabbcf542'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('17419a4f-5c27-4283-9437-7ee5496fb057'), null=True),
        ),
    ]
