# Generated by Django 2.2.2 on 2019-09-11 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0022_auto_20190911_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ad415477-d7f6-4642-a551-bc689e16d6cf'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('87338b88-2d5e-44ee-afc9-7cb942ba624f'), null=True),
        ),
    ]
