# Generated by Django 2.2.2 on 2019-09-11 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0023_auto_20190911_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d4fe8a27-94f9-4334-bd4f-3cd19ccbc34c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6f83e01c-33ad-4a8c-acc1-d9cf86415686'), null=True),
        ),
    ]
