# Generated by Django 2.2.2 on 2019-09-12 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0024_auto_20190911_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fad5cb11-7dbf-43cb-9300-4569b6c38ad1'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b90290cc-1994-4c07-b784-dd7f3a98051e'), null=True),
        ),
    ]
