# Generated by Django 2.2.2 on 2019-09-12 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0025_auto_20190912_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('439271ce-4e82-4c1a-950f-7f2177443bf9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bb026517-b4b7-4360-9144-1a16ffc6f6a7'), null=True),
        ),
    ]
