# Generated by Django 2.2.2 on 2019-09-15 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0026_auto_20190912_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bfa84106-6c75-4ffc-a6c5-7eb7bc5e152a'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('392f9442-04da-43cb-a06f-7fcd02854dd1'), null=True),
        ),
    ]
