# Generated by Django 2.2.2 on 2019-09-15 21:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0027_auto_20190915_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3d734253-8a08-473b-99a0-ecb1ca7bce3c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9adb3658-bf9c-4561-9e37-566fad73bed1'), null=True),
        ),
    ]
