# Generated by Django 2.2.2 on 2019-09-15 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0028_auto_20190915_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('dcd95407-f8ac-4a35-8e7a-0e911b50b89b'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('144cc13e-7c83-4400-888b-21304c416109'), null=True),
        ),
    ]
