# Generated by Django 2.2.2 on 2019-09-15 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0029_auto_20190915_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('42b003ae-038a-4051-b19b-6f9508b7063d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('31608601-ff19-4fc5-bc41-96679dab2d08'), null=True),
        ),
    ]
