# Generated by Django 2.2.2 on 2019-09-16 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0030_auto_20190915_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6749fc98-2dcb-4db0-a30f-8b50d1d500d6'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ecd0941b-5d32-4432-a6e8-db53e4a8f2eb'), null=True),
        ),
    ]
