# Generated by Django 2.2.2 on 2019-09-16 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0031_auto_20190916_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3cb99e54-02b1-4e30-817b-7dd68538c559'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fca7ad51-8e0a-4ff1-bd0c-88f7e9b92afb'), null=True),
        ),
    ]
