# Generated by Django 2.2.2 on 2019-09-16 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0032_auto_20190916_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a5de2236-c171-4aac-9f2d-cf945d46116f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('07ebb6aa-4bb5-42ec-9076-bacaac3aad5e'), null=True),
        ),
    ]
