# Generated by Django 2.2.2 on 2019-09-17 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0033_auto_20190916_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2df3ddc0-0921-4b95-b58f-53018236b9f8'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5421c3dd-a8f8-4b60-b2f5-db953fddf6f1'), null=True),
        ),
    ]
