# Generated by Django 2.2.2 on 2019-09-17 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0034_auto_20190917_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('63368aac-689e-4701-bf95-09cae534f38a'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6db55805-aeee-4c5e-ba89-794e2557aafb'), null=True),
        ),
    ]
