# Generated by Django 2.2.2 on 2019-09-21 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0035_auto_20190917_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d9ff7e2d-203e-4735-ba8e-95a3318fb3e6'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('724f4319-b64b-4639-8e0e-554139b4131e'), null=True),
        ),
    ]
