# Generated by Django 2.2.2 on 2019-09-23 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0036_auto_20190921_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('72a59bb8-087c-4a3e-81c2-13580858a3f9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6d83eec7-2fca-48d3-bea2-58a0a4ce46b4'), null=True),
        ),
    ]
