# Generated by Django 2.2.2 on 2019-10-06 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0037_auto_20190923_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0ec6abda-acd5-489f-a48f-a2b79a9de1bc'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9f4cd6f4-31dd-44ba-9d02-64c72b61c009'), null=True),
        ),
    ]
