# Generated by Django 2.2.2 on 2019-10-06 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0038_auto_20191006_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9800bcb7-543f-405b-bea9-d41ba505dcd7'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('306084be-2ef7-454b-ad65-ecf4a664ec0f'), null=True),
        ),
    ]
