# Generated by Django 2.2.2 on 2019-10-06 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0039_auto_20191006_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8e10499f-e014-48e5-bf62-48467754fc44'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c34ff049-94e1-4290-b352-e17cba329556'), null=True),
        ),
    ]
