# Generated by Django 2.2.2 on 2019-10-06 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0040_auto_20191006_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('72acc261-be06-4a73-be46-63704249398c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('56f098a5-52a3-4127-b984-40f1ca44cde5'), null=True),
        ),
    ]
