# Generated by Django 2.2.2 on 2019-10-06 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0041_auto_20191006_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a8a18fee-fa81-4f1b-9cfe-83c9c849d920'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('22c4031b-3ec7-481f-abab-6d84360db943'), null=True),
        ),
    ]
