# Generated by Django 2.2.2 on 2019-10-06 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0042_auto_20191006_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('26250b88-c7b4-4e4b-9747-0340047545d9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7547afb8-f727-4652-b6f4-254b9bc244a7'), null=True),
        ),
    ]
