# Generated by Django 2.2.2 on 2019-10-06 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0043_auto_20191006_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3f7bfd60-b02b-47f5-9cd9-438ab13199d0'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('162a162f-bf20-45f2-80da-631224bbfae4'), null=True),
        ),
    ]
