# Generated by Django 2.2.2 on 2019-10-06 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0044_auto_20191006_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bdf16747-4fc2-44b1-a2e4-e63330d477c6'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('883de47a-3fdc-4a7c-b1a6-8d206609756f'), null=True),
        ),
    ]
