# Generated by Django 2.2.2 on 2019-10-06 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0045_auto_20191006_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c951243e-1160-49d4-8f36-9a032e75adda'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8294739c-bc41-42e5-868f-6d5d963ca7c4'), null=True),
        ),
    ]
