# Generated by Django 2.2.2 on 2019-10-06 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0046_auto_20191006_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6230b5e7-5f06-4bed-894a-adaba2920c30'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e8272a20-61be-40ce-8c31-efe7c154a55c'), null=True),
        ),
    ]
