# Generated by Django 2.2.2 on 2019-10-07 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0047_auto_20191006_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e832cb56-299f-43b5-aab5-93a2a412ec86'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f3559c37-1bff-4436-8ccb-16d8cef7a788'), null=True),
        ),
    ]
