# Generated by Django 2.2.2 on 2019-10-07 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0048_auto_20191007_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('eac23cb8-c817-4a92-a45d-a9066b844907'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5e4c9027-9cd5-4570-8e9b-f5ea661800c8'), null=True),
        ),
    ]
