# Generated by Django 2.2.2 on 2019-10-07 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0049_auto_20191007_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1d2d887e-fb99-4a9f-9f11-3c693315b586'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ca427905-a208-4e16-bd28-31e8cb940171'), null=True),
        ),
    ]
