# Generated by Django 2.2.2 on 2019-10-07 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0050_auto_20191007_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2c672b2c-27b0-4d92-8611-0003496cbe80'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2cebc4ae-6e6b-491a-a06f-494d440b8f57'), null=True),
        ),
    ]
