# Generated by Django 2.2.2 on 2019-10-08 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0051_auto_20191007_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3c5a5710-9e74-45a7-b363-7853e2acc810'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ddc8fad7-dd2b-4ec9-a319-de4b94bf403a'), null=True),
        ),
    ]
