# Generated by Django 2.2.2 on 2019-10-09 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0052_auto_20191008_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7d455e2a-62d0-4660-995c-854d1d2c5b32'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('06d805dd-2da6-4de8-b3b4-c3a0198ec688'), null=True),
        ),
    ]
