# Generated by Django 2.2.2 on 2019-10-09 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0053_auto_20191009_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('51735f98-becb-4334-902d-e9aaa759c262'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a6338285-a296-4098-8f1e-b12626f0c301'), null=True),
        ),
    ]
