# Generated by Django 2.2.2 on 2019-10-10 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0054_auto_20191009_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c8e623d7-e77e-453f-95a4-ac1e85bc0d0c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a97da337-5182-48fa-8e3e-728d48d1dea0'), null=True),
        ),
    ]
