# Generated by Django 2.2.2 on 2019-10-11 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0055_auto_20191010_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('428bff0a-fb96-4143-9acd-af95a945f858'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('67fbec84-4820-4081-9645-99758a8dd562'), null=True),
        ),
    ]
