# Generated by Django 2.2.2 on 2019-10-12 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0056_auto_20191011_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8a7c08b2-4953-4ddb-9298-af8e439a2a3f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1feea6dc-714d-459f-8ce0-8a5e9ceb6686'), null=True),
        ),
    ]
