# Generated by Django 2.2.2 on 2019-10-12 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0057_auto_20191012_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('17bf05ed-9872-49bf-a51d-0043a25fdaf9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6ed08fcc-dba7-485a-bcbd-4df0ba815d2e'), null=True),
        ),
    ]
