# Generated by Django 2.2.2 on 2019-10-12 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0058_auto_20191012_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6b642c16-abdd-480f-8f1e-28fa7a54400d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8523dc38-e9a9-4d71-b2f9-d6080239b87e'), null=True),
        ),
    ]
