# Generated by Django 2.2.2 on 2019-10-12 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0059_auto_20191012_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('83c7c5e6-52ac-4b6d-9fd5-2c6ef80ec551'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9efc1b3a-85f6-48af-814c-8bb74a9422d6'), null=True),
        ),
    ]
