# Generated by Django 2.2.2 on 2019-10-12 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0060_auto_20191012_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c286db0f-213f-42ea-aa03-858467c10eb9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e973a3ed-0833-4640-9b7f-88c6d700c0f5'), null=True),
        ),
    ]
