# Generated by Django 2.2.2 on 2019-10-12 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0061_auto_20191012_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('def70d3e-20db-487c-b88c-baf19e8519d8'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3e7fc396-f2c3-41f9-ba7c-a9673da1527b'), null=True),
        ),
    ]
