# Generated by Django 2.2.2 on 2019-10-12 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0062_auto_20191012_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7b196d43-2f54-40e3-a0f0-9bf189f79d9b'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9656665c-4c6e-48d2-b081-0131650d7f48'), null=True),
        ),
    ]
