# Generated by Django 2.2.2 on 2019-10-12 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0063_auto_20191012_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2e24606a-3f63-4ace-8e00-c14e79983988'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('34a5eaf6-c5d0-45c1-ac8c-1c346ea83f00'), null=True),
        ),
    ]
