# Generated by Django 2.2.2 on 2019-10-12 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0064_auto_20191012_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b58cc345-9b4e-4ac5-893f-44949a286e3c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('21ce1b3c-9834-4d4a-8772-6d30db74c5ae'), null=True),
        ),
    ]
