# Generated by Django 2.2.2 on 2019-10-12 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0065_auto_20191012_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0813c4bd-4e3b-4016-b225-d61f29f6e1ad'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bc16a061-db9e-4642-9736-b4af3dbff9dc'), null=True),
        ),
    ]
