# Generated by Django 2.2.2 on 2019-10-12 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0066_auto_20191012_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cf94e013-9dbd-4997-b76f-16f3f2ec63da'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4ca55a84-8587-4638-add0-37bf4171670f'), null=True),
        ),
    ]
