# Generated by Django 2.2.2 on 2019-10-12 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0067_auto_20191012_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('36e54e3a-b692-4ea7-be17-98dd945de1e8'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('504bebad-e5c0-463f-a04c-af2bf8b472b8'), null=True),
        ),
    ]
