# Generated by Django 2.2.2 on 2019-10-12 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0068_auto_20191012_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ba7031d1-a54d-4270-8761-aa2d47da1983'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('007abc1a-bee4-465f-afd6-de4b0f35c662'), null=True),
        ),
    ]
