# Generated by Django 2.2.2 on 2019-10-12 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0069_auto_20191012_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('40442812-0c52-48d4-8dea-72bfa223ab5b'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('850ab03c-7e05-4d82-b4dc-638db27fdd7e'), null=True),
        ),
    ]
