# Generated by Django 2.2.2 on 2019-10-12 11:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0070_auto_20191012_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('571feaad-3860-4b59-95db-35bc0758b208'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a3b5e119-fb3c-4c11-bd03-827f327fb3a7'), null=True),
        ),
    ]
