# Generated by Django 2.2.2 on 2019-10-12 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0071_auto_20191012_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2cbb1262-d804-4c39-bc56-66e5b77910b4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ac24538e-b742-4080-aa16-db7b95b2e140'), null=True),
        ),
    ]
