# Generated by Django 2.2.2 on 2019-10-12 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0072_auto_20191012_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a0bd6dbe-101e-4437-b4af-8e7884dbd545'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('69116dc8-c30a-43c0-b21a-24f195bfbb03'), null=True),
        ),
    ]
