# Generated by Django 2.2.2 on 2019-10-12 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0073_auto_20191012_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('36adf78d-4d3a-4046-8326-0e0e7ce7027e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7a46846c-ee12-44d4-94b9-77a7dfd1b57d'), null=True),
        ),
    ]
