# Generated by Django 2.2.2 on 2019-10-12 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0074_auto_20191012_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2ef9fcc6-c234-4443-9121-95cbb389c68b'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e026644c-53a8-4869-83be-bd8f351ea4a1'), null=True),
        ),
    ]
