# Generated by Django 2.2.2 on 2019-10-12 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0075_auto_20191012_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('91043737-2f46-4590-810d-418c7b777226'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7857706c-f847-4c3b-b5c3-333e1ce714ec'), null=True),
        ),
    ]
