# Generated by Django 2.2.2 on 2019-10-12 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0076_auto_20191012_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b37d3b17-abb1-4f42-9461-8f0cfcc978b5'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8763ce8b-7a20-4764-a6cf-e99340c3e8ac'), null=True),
        ),
    ]
