# Generated by Django 2.2.2 on 2019-10-12 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0077_auto_20191012_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8b3f1873-d4fc-451a-aa61-a1105ddc73ae'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a1e2f61e-6d76-4922-824a-2a9a6985c67f'), null=True),
        ),
    ]
