# Generated by Django 2.2.2 on 2019-10-12 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0078_auto_20191012_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('19bd9205-2877-4031-98d6-94a6027fe0b4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('45f28fcc-3c16-4cc5-97a4-fa1495775d7c'), null=True),
        ),
    ]
