# Generated by Django 2.2.2 on 2019-10-12 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0079_auto_20191012_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('50c49396-e099-4ddf-bf97-6be0d5f6901c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('20c4af04-59e9-4f38-959a-dd6335253e77'), null=True),
        ),
    ]
