# Generated by Django 2.2.2 on 2019-10-12 15:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0080_auto_20191012_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('33830082-6642-4824-89df-1effcee206b1'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3d4ba2ee-8684-4b82-99eb-8a8a59772ffd'), null=True),
        ),
    ]
