# Generated by Django 2.2.2 on 2019-10-12 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0081_auto_20191012_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e669e613-386b-4ea2-a274-4b6f6ba9e20a'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b8344304-ffa5-4d6a-b7a5-70d1f7f08ddb'), null=True),
        ),
    ]
