# Generated by Django 2.2.2 on 2019-10-12 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0082_auto_20191012_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('05dbccb7-7397-44be-ac7c-c1b465c068c3'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4c4b9603-74b3-44a0-a525-bf462c961a08'), null=True),
        ),
    ]
