# Generated by Django 2.2.2 on 2019-10-12 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0083_auto_20191012_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e325464a-bfb9-4f42-9b3e-57a18d364f91'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('68b2ac5c-4f1b-406b-9b09-8ca5d5dfaf36'), null=True),
        ),
    ]
