# Generated by Django 2.2.2 on 2019-10-12 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0084_auto_20191012_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('94214b14-87b0-45e0-8c3e-a02fb8e2b938'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0f257298-71b9-40cf-9efa-1124121f4957'), null=True),
        ),
    ]
