# Generated by Django 2.2.2 on 2019-10-12 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0085_auto_20191012_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7a804439-35b6-49b1-b62a-d035bb06d29f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3032a215-73f4-4cb8-a217-df3e9d3df9a5'), null=True),
        ),
    ]
