# Generated by Django 2.2.2 on 2019-10-12 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0086_auto_20191012_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('92333f15-f1b1-496b-ac07-4371c1fc31d5'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7615798d-0a44-4598-95b3-3d4b38839d9b'), null=True),
        ),
    ]
