# Generated by Django 2.2.2 on 2019-10-12 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0087_auto_20191012_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('34990e11-1cc5-40e4-b30c-0920775b612c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5b6b6b22-d485-4ff9-b10a-249995228f0b'), null=True),
        ),
    ]
