# Generated by Django 2.2.2 on 2019-10-12 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0088_auto_20191012_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('70bbffd1-0059-4f5f-bd48-12c0442644c1'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d6f62f6d-a9fb-4018-9eec-e417762d82a3'), null=True),
        ),
    ]
