# Generated by Django 2.2.2 on 2019-10-12 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0089_auto_20191012_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0d1bd0af-df5c-44e0-948e-bbaf00d2d553'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f2a42234-3d32-455d-895f-6fc850a751e2'), null=True),
        ),
    ]
