# Generated by Django 2.2.2 on 2019-10-12 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0090_auto_20191012_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e18559ec-e6f3-44b0-8b2f-e47b8cbe4cd4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a8c497d2-f266-4fcd-b891-350dd71adf36'), null=True),
        ),
    ]
