# Generated by Django 2.2.2 on 2019-10-13 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0091_auto_20191012_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('390b6bc0-2783-49af-81c4-c3f0a40628d1'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a3e991c2-68dd-4782-8186-b349888c6411'), null=True),
        ),
    ]
