# Generated by Django 2.2.2 on 2019-10-13 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0092_auto_20191013_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8ef38a1a-80d5-4933-9050-e4ed4dbff6f7'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('66f8695d-0901-48ff-860f-e23089532c0d'), null=True),
        ),
    ]
