# Generated by Django 2.2.2 on 2019-10-13 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0093_auto_20191013_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('45b9e80b-907f-46c8-8aad-8f12acfe3db3'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('54223dba-9353-4338-8de9-d225af500b7b'), null=True),
        ),
    ]
