# Generated by Django 2.2.2 on 2019-10-13 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0094_auto_20191013_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f439092a-7e19-4175-912f-11fea6af332f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('50941acd-30e6-4abb-87ba-a184baf4e879'), null=True),
        ),
    ]
