# Generated by Django 2.2.2 on 2019-10-13 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0095_auto_20191013_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1afdee9b-0a34-4242-92e5-a1d2941f05f2'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('57aa76a0-0630-4c0d-a13a-ec169b308207'), null=True),
        ),
    ]
