# Generated by Django 2.2.2 on 2019-10-14 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0096_auto_20191013_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('054f02a9-ddb1-4a89-a749-549d994b604d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('94e35c47-beaf-471b-bbaa-d0ee8aac2d67'), null=True),
        ),
    ]
