# Generated by Django 2.2.2 on 2019-10-14 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0097_auto_20191014_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6a216de3-a94f-4d62-9c49-e9c985485ce5'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e94e4e8f-5bfc-4cde-bafe-872d293d2fa9'), null=True),
        ),
    ]
