# Generated by Django 2.2.2 on 2019-10-14 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0098_auto_20191014_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0790cfff-82c6-486c-8558-8aa703726021'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1170478f-52f6-4d10-b536-036ffca6ef18'), null=True),
        ),
    ]
