# Generated by Django 2.2.2 on 2019-10-14 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0099_auto_20191014_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f4ce82af-36b1-4469-be3c-4d1979f9c7b0'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b4e36437-e777-4be3-9fe0-709e7faa42c1'), null=True),
        ),
    ]
