# Generated by Django 2.2.2 on 2019-10-14 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0100_auto_20191014_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0a0896bb-16cf-4aed-bed8-0b013f121d1e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f7d091a6-898e-44f3-9bb7-719ac6ee2797'), null=True),
        ),
    ]
