# Generated by Django 2.2.2 on 2019-10-14 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0101_auto_20191014_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('338b21ce-79c6-4977-8a43-0fddff32861a'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cb6d125b-1ccf-4784-b78d-f59356f999e7'), null=True),
        ),
    ]
