# Generated by Django 2.2.2 on 2019-10-14 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0102_auto_20191014_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2a7d2286-4663-46df-8bcc-f30dca8a70d5'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7d318376-88de-4e34-b43a-916dfb4f4170'), null=True),
        ),
    ]
