# Generated by Django 2.2.2 on 2019-10-14 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0103_auto_20191014_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0e8740ee-86bb-4c8a-a749-9f506ff4de9c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0d83bfd2-8efa-4e74-959f-a63158dee0df'), null=True),
        ),
    ]
