# Generated by Django 2.2.2 on 2019-10-19 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0104_auto_20191014_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2307ff62-7930-4bc2-b558-807a4c42dc5d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d6d56419-d685-46f4-bdf4-d71d7c416864'), null=True),
        ),
    ]
