# Generated by Django 2.2.2 on 2019-10-19 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0105_auto_20191019_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b510c6e2-2647-4496-88c9-8e90f9914be1'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c6908684-ada0-49a7-b521-2e61575ffc75'), null=True),
        ),
    ]
