# Generated by Django 2.2.2 on 2019-10-19 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0106_auto_20191019_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5d569af3-ddf1-427c-9616-40e9191fbca6'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('299afefe-1614-494a-9fb5-a2699c0c4e7c'), null=True),
        ),
    ]
