# Generated by Django 2.2.2 on 2019-10-21 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0107_auto_20191019_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ab35b884-a3b0-4780-b8af-fe872a4a2c22'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8a082b28-7e7c-434f-9e4b-383ed7f68d11'), null=True),
        ),
    ]
