# Generated by Django 2.2.2 on 2019-10-22 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0108_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3d57cfa9-ac14-4e57-8516-8d7102114f0e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('44f0c830-4455-4925-b781-aa70d97cf443'), null=True),
        ),
    ]
