# Generated by Django 2.2.2 on 2019-10-21 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0108_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b6fe106e-aedf-46ff-a0e5-c42d43bf0e8e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('301bbd2c-4549-499c-b100-7a7f1af3c0fa'), null=True),
        ),
    ]
