# Generated by Django 2.2.2 on 2019-10-22 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0109_auto_20191022_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('84e95841-ff1c-432f-9db0-19c77ac06857'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('32684c0e-5edf-430d-b762-531895381652'), null=True),
        ),
    ]
