# Generated by Django 2.2.2 on 2019-10-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0109_auto_20191022_1117'),
        ('exrate', '0109_auto_20191021_1218'),
    ]

    operations = [
    ]
