# Generated by Django 2.2.2 on 2019-10-22 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0110_auto_20191022_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ae37ccb8-81c1-47c8-9a3e-b32849cd189e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2cb7a126-242c-4e15-9a2b-9386f1515fa3'), null=True),
        ),
    ]
