# Generated by Django 2.2.2 on 2019-10-25 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0111_auto_20191022_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('789cf88b-8244-43d6-9106-4e0b35649210'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d95b1e39-e612-4a6c-bcfb-6f5b752a69e1'), null=True),
        ),
    ]
