# Generated by Django 2.2.2 on 2019-10-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0110_merge_20191022_1352'),
        ('exrate', '0111_auto_20191022_2136'),
    ]

    operations = [
    ]
