# Generated by Django 2.2.2 on 2019-10-25 21:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0112_auto_20191025_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('567605ef-6a64-4936-b592-a18c0fe45ad0'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1c77713e-7533-4341-b431-cfb15e9e1f28'), null=True),
        ),
    ]
