# Generated by Django 2.2.2 on 2019-10-25 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0113_auto_20191025_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('647faee8-d294-4cff-9f3e-6895f2dde916'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('95d29fc0-3be4-4b8c-8409-2ea558173293'), null=True),
        ),
    ]
