# Generated by Django 2.2.2 on 2019-10-25 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0114_auto_20191025_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4c412608-c641-4a16-9d92-a13bf3917e7a'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7c3b3cc3-62d0-47c7-83e6-972d5aa5a040'), null=True),
        ),
    ]
