# Generated by Django 2.2.2 on 2019-10-27 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0116_auto_20191025_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'systemEnvs',
            },
        ),
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e05ae7c0-2787-4865-9a96-3e06626b06cd'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a73a267d-cfab-4862-8816-9fb5073a4fdf'), null=True),
        ),
    ]
