# Generated by Django 2.2.2 on 2019-11-07 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0117_auto_20191027_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('dbcc77ee-62e7-48bf-a5cb-9131187081f4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cf454421-cf3b-4d7c-91fb-bab7da7299ea'), null=True),
        ),
    ]
