# Generated by Django 2.2.2 on 2019-11-07 22:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0118_auto_20191107_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f6152e1f-b402-42f3-9fe8-8de2bc9e48be'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('25b97ad3-3066-4193-aba7-0d5b4837a10e'), null=True),
        ),
    ]
