# Generated by Django 2.2.2 on 2019-11-11 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0119_auto_20191107_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('44cfb7e6-26a5-4b43-aa02-630fd11782f3'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('19daa8ed-a318-4a3e-8ae2-de033db4762a'), null=True),
        ),
    ]
