# Generated by Django 2.2.2 on 2019-11-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0120_auto_20191111_0949'),
        ('exrate', '0117_merge_20191025_2328'),
    ]

    operations = [
    ]
