# Generated by Django 2.2.2 on 2019-11-18 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0121_merge_20191112_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5fcbd938-a3c4-4b76-978c-9c5eefb8300d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b7780390-34b0-4016-aa6b-cc826319f2d6'), null=True),
        ),
    ]
