# Generated by Django 2.2.2 on 2019-11-18 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0122_auto_20191118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6d317642-ba82-4809-bcf4-3db3abd15386'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('47733252-b38f-434e-a197-683d99a7310c'), null=True),
        ),
    ]
