# Generated by Django 2.2.2 on 2019-11-18 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0123_auto_20191118_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e173f8f0-6231-41e1-8a65-156c34623623'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3a29250e-2b2e-4664-99d4-9400a27651fa'), null=True),
        ),
    ]
