# Generated by Django 2.2.2 on 2019-11-19 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0124_auto_20191118_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('caf0050e-723b-4da3-9c76-71904e56b3c4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('245cda35-8f96-4078-9d07-ad24429eb9b5'), null=True),
        ),
    ]
