# Generated by Django 2.2.2 on 2019-11-19 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0126_auto_20191119_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0973f377-ce16-4c55-9b0f-c0ed2923041c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d28afda4-658b-4f33-b135-8c089daa8c10'), null=True),
        ),
    ]
