# Generated by Django 2.2.2 on 2019-11-19 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0127_auto_20191119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ff63e945-f467-46eb-850f-55d544d662df'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('74017710-685b-453a-81cd-fcc36fc11dcd'), null=True),
        ),
    ]
