# Generated by Django 2.2.2 on 2019-11-19 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0128_auto_20191119_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bba5259a-1626-4be4-a0e3-bb7f323405f6'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('07a0b663-1395-4a12-9c56-cc1d7c9323e9'), null=True),
        ),
    ]
