# Generated by Django 2.2.2 on 2019-11-20 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0129_auto_20191119_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a0b2bebd-9b15-4194-a21a-3bbd0c949a56'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cb15df8f-0b85-4d9c-bc97-b6c1ddeaa4cd'), null=True),
        ),
    ]
