# Generated by Django 2.2.2 on 2019-11-20 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0130_auto_20191120_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('de4bae0f-384d-4393-877e-2f422e7315c9'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5e6544bc-b03d-4694-8dff-f9c9e1cfea48'), null=True),
        ),
    ]
