# Generated by Django 2.2.2 on 2019-11-20 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0131_auto_20191120_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cec13c88-a98f-48a5-bc7e-93369accb3de'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a9f2fcfe-fac2-48ba-830e-3e51ef1faee9'), null=True),
        ),
    ]
