# Generated by Django 2.2.2 on 2019-11-21 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0134_auto_20191121_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('469dd3fd-8c09-45ec-889c-e9f043651916'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fe2f66d7-bfc1-4a06-95d1-7849b594fedc'), null=True),
        ),
    ]
