# Generated by Django 2.2.2 on 2019-11-21 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0135_auto_20191121_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d93e69e6-326d-4e3a-9dc3-eda847b5a7dd'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1f326bb0-f3b6-4d98-bc5d-e01a4bc64116'), null=True),
        ),
    ]
