# Generated by Django 2.2.2 on 2019-11-21 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0136_auto_20191121_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2956fee3-d8da-4d5e-908a-1a28ae2e6b2f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('240e927b-ac4d-4724-ae84-58081bf00d8c'), null=True),
        ),
    ]
