# Generated by Django 2.2.2 on 2019-11-21 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0138_auto_20191121_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('33824477-8613-4a76-95e0-98b72e625cc8'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2d847697-c25f-44b2-85ff-c23d609ae621'), null=True),
        ),
    ]
