# Generated by Django 2.2.2 on 2019-11-21 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0139_auto_20191121_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('22c58914-9807-494b-a9b4-ca577b130bf4'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e8351634-c94f-4894-8843-099c0a5aa951'), null=True),
        ),
    ]
