# Generated by Django 2.2.2 on 2019-11-21 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0140_auto_20191121_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5bb4f241-94d9-4d4d-8545-dba84f4ae1fc'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c32e8277-2342-4bbb-a170-147f10516df9'), null=True),
        ),
    ]
