# Generated by Django 2.2.2 on 2019-11-21 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0141_auto_20191121_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7b592a5f-2924-4215-a762-6b2f5b8958e8'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bb578e51-29b2-4b8f-bbac-27eeb8a1dd59'), null=True),
        ),
    ]
