# Generated by Django 2.2.2 on 2019-11-21 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0142_auto_20191121_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('075674a1-97b6-4e94-aa56-1877383f6c6e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a3a3737c-ac3b-4fec-9056-dfcbe2bbe6d7'), null=True),
        ),
    ]
