# Generated by Django 2.2.2 on 2019-11-22 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0143_auto_20191121_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ea9eb84c-cc30-4244-8d04-1998b6922d10'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c0285824-72fb-413b-b1d4-04d380e7fac0'), null=True),
        ),
    ]
