# Generated by Django 2.2.2 on 2019-11-22 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0144_auto_20191122_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0536ba2b-00fb-41de-a504-4b9b79a19418'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('04249512-db88-406f-86bd-0afc36339eff'), null=True),
        ),
    ]
