# Generated by Django 2.2.2 on 2019-11-22 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0145_auto_20191122_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('18bf277a-72e8-40fa-be68-3993bb326812'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('703ba549-6a7b-482a-8f9f-e0882a00d858'), null=True),
        ),
    ]
