# Generated by Django 2.2.2 on 2019-11-22 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0147_auto_20191122_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('893b1e8f-6e5d-437c-a937-c040e6359933'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5403a95f-c16f-40e5-8c75-492c67e08586'), null=True),
        ),
    ]
