# Generated by Django 2.2.2 on 2019-11-22 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0148_auto_20191122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5240f7d8-0eaa-4bf0-a1f5-3ba787599622'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1d10a9b4-2dcc-478c-b866-ccd7f258c4e3'), null=True),
        ),
    ]
