# Generated by Django 2.2.2 on 2019-11-24 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0149_auto_20191122_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3fefd57d-1646-4bba-8709-37c600933f98'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('68f47d8f-40ca-4fad-a12a-4c3ab7d8eec5'), null=True),
        ),
    ]
