# Generated by Django 2.2.2 on 2019-11-28 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0151_auto_20191128_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7567f469-94bd-4b40-a5b9-1486824e3c9f'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9aa69613-1954-4eb2-bb5c-0944c8b10766'), null=True),
        ),
    ]
