# Generated by Django 2.2.2 on 2019-11-30 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0152_auto_20191128_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a2d13480-7d8e-43a2-b367-dc1beb70854d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2ff18fcb-9383-44b1-b981-27469e7dc2e1'), null=True),
        ),
    ]
