# Generated by Django 2.2.2 on 2019-11-30 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0153_auto_20191130_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('33e43bb1-4da3-4b21-aaff-00c13bc2e964'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f3876ffc-37d4-4ec0-9ab8-5b46abd4ccea'), null=True),
        ),
    ]
