# Generated by Django 2.2.2 on 2019-11-30 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0154_auto_20191130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a6d1b24f-49b0-4bb6-a138-acc1954b9d29'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('78aa2013-42c8-43f2-b9dd-3553700e02fe'), null=True),
        ),
    ]
