# Generated by Django 2.2.2 on 2019-12-08 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0155_auto_20191130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4411cefe-5831-4f44-9639-aee234878db0'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3671b6a6-4ee2-4548-af29-3ad5fe57b69e'), null=True),
        ),
    ]
