# Generated by Django 2.2.2 on 2019-12-12 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0156_auto_20191208_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f2864dec-5f8b-4d81-98d3-e9709910c53e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0db07119-88f2-4686-a7a4-17b7fef85823'), null=True),
        ),
    ]
