# Generated by Django 2.2.2 on 2019-12-12 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0157_auto_20191212_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('69e740b1-c024-43e1-a0b2-e7ee133dde9d'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4367c2cf-fd2e-48f8-8062-5a66124fa89c'), null=True),
        ),
    ]
