# Generated by Django 2.2.2 on 2019-12-17 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0159_auto_20191217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d9b670cb-02d4-41e4-ac2a-a0c6926429ab'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('84db671d-a2f9-41cb-bd3c-e77b54e51984'), null=True),
        ),
    ]
