# Generated by Django 2.2.2 on 2019-12-22 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0161_auto_20191218_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1e2c8a5e-7df0-4e45-b69a-58d8d9ef2867'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('2fb0cfd8-019b-48e0-a9a8-dad42a5db099'), null=True),
        ),
    ]
