# Generated by Django 2.2.2 on 2019-12-22 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0162_auto_20191222_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('631a6af7-333f-4767-8ade-150c404e9afa'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ce8d6cd0-3e5d-4dac-b822-57f4d8d8e92f'), null=True),
        ),
    ]
