# Generated by Django 2.2.2 on 2019-12-22 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0163_auto_20191222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bc71ee00-94c8-49f3-baf7-1e090dfbefab'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('88a93edb-6fd6-4728-9ab1-426d1c5cac99'), null=True),
        ),
    ]
