# Generated by Django 2.2.2 on 2019-12-24 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0165_auto_20191224_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0d7b9859-dd9c-4c37-b550-20ad9a1c214c'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e1b098fc-e76a-4948-a1ea-2b4c8fd100d8'), null=True),
        ),
    ]
