# Generated by Django 2.2.2 on 2019-12-24 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0166_auto_20191224_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3743dbfe-0cea-4a38-92ce-289bf5de4997'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fcb1d7fe-139a-445e-adc1-250ac84366cf'), null=True),
        ),
    ]
