# Generated by Django 2.2.2 on 2019-12-25 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0167_auto_20191224_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('05d9ceb3-7a7c-403d-8ae4-6b6efe031dce'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3c71ccd2-b4f3-41de-adf5-a7661225d36c'), null=True),
        ),
    ]
