# Generated by Django 2.2.2 on 2019-12-28 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0168_auto_20191225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9348f6b7-c6e4-4c85-8762-c68d5199576b'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('06860de9-d0e8-4b9a-a3c7-75f41d51d672'), null=True),
        ),
    ]
