# Generated by Django 2.2.2 on 2019-12-29 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0169_auto_20191228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5b7a9cff-dae0-47c4-b2cb-f464cde6108e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d3a2f05e-75bd-4ef9-b465-31e055b4188e'), null=True),
        ),
    ]
