# Generated by Django 2.2.2 on 2020-01-08 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0170_auto_20191229_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('708694eb-ef59-4368-97e7-6e1d90e14b4e'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('35ca79fb-0164-45d4-bef2-1fa29ac9fe4e'), null=True),
        ),
    ]
