# Generated by Django 2.2.2 on 2020-01-08 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0171_auto_20200108_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('26245177-6be1-41b1-99a6-63c2de6c9169'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('48bd3754-3a58-48cd-8cb6-dbe0eb405d26'), null=True),
        ),
    ]
