# Generated by Django 2.2.2 on 2020-01-08 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exrate', '0172_auto_20200108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ab33464e-ba12-4b26-bb68-dd2d4bbe3906'), null=True),
        ),
        migrations.AlterField(
            model_name='bonusdetail',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('081d2b87-9986-4b2f-9e3e-01bc28f909bf'), null=True),
        ),
    ]
