TYPE=VIEW
query=select `ci`.`created_at` AS `date`,`ci`.`po_id` AS `po_id`,`ci`.`product_id` AS `product_id`,`cat`.`name` AS `catalogue`,`subcat`.`name` AS `subcatalogue`,`ps`.`paid_customer` AS `paid_customer`,`ps`.`paid_vendor` AS `paid_vendor`,`pd`.`product_code` AS `product_code`,`pd`.`postimage` AS `postimage`,`pd`.`thumbImage` AS `thumbimage`,`pd`.`name` AS `name_cn`,`pd`.`name_jp` AS `name_jp`,`pd`.`tablets` AS `tablets`,`pd`.`unit` AS `unit`,`pd`.`r_price` AS `r_price`,`pd`.`b_price` AS `b_price`,`pd`.`o_price` AS `o_price`,`ci`.`qty` AS `Qty`,`ci`.`total_r_price` AS `total_r_price`,`ci`.`total_b_price` AS `total_b_price`,`ci`.`total_o_price` AS `total_o_price`,`cs`.`name` AS `customer_name`,`cs`.`postcode` AS `customer_postcode`,`cs`.`phone` AS `customer_phone`,`cs`.`address1` AS `customer_address1`,`cs`.`address2` AS `customer_address2`,`us`.`name` AS `staff_name`,`ps`.`user_id` AS `user_id`,`ps`.`status` AS `status`,`ps`.`vendor_id` AS `vendor_id` from ((((((`misawa2020`.`cartitems` `ci` left join `misawa2020`.`products` `pd` on((`ci`.`product_id` = `pd`.`id`))) left join `misawa2020`.`catalogues` `cat` on((`pd`.`catalogue_id` = `cat`.`id`))) left join `misawa2020`.`pos` `ps` on((`ci`.`po_id` = `ps`.`id`))) left join `misawa2020`.`subcatalogues` `subcat` on((`pd`.`subcatalogue_id` = `subcat`.`id`))) left join `misawa2020`.`users` `us` on((`ps`.`user_id` = `us`.`id`))) left join `misawa2020`.`customers` `cs` on((`ps`.`customer_id` = `cs`.`id`)))
md5=80303ccd1c3e7604f4973136e073faf7
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2019-10-18 23:33:50
create-version=1
source=SELECT\n   `ci`.`created_at` AS `date`,\n   `ci`.`po_id` AS `po_id`,\n   `ci`.`product_id` AS `product_id`,\n   `cat`.`name` AS `catalogue`,\n   `subcat`.`name` AS `subcatalogue`,\n   `ps`.`paid_customer` AS `paid_customer`,\n   `ps`.`paid_vendor` AS `paid_vendor`,\n   `pd`.`product_code` AS `product_code`,\n   `pd`.`postimage` AS `postimage`,\n   `pd`.`thumbImage` AS `thumbimage`,\n   `pd`.`name` AS `name_cn`,\n   `pd`.`name_jp` AS `name_jp`,\n   `pd`.`tablets` AS `tablets`,\n   `pd`.`unit` AS `unit`,\n   `pd`.`r_price` AS `r_price`,\n   `pd`.`b_price` AS `b_price`,\n   `pd`.`o_price` AS `o_price`,\n   `ci`.`qty` AS `Qty`,\n   `ci`.`total_r_price` AS `total_r_price`,\n   `ci`.`total_b_price` AS `total_b_price`,\n   `ci`.`total_o_price` AS `total_o_price`,\n   `cs`.`name` AS `customer_name`,\n   `cs`.`postcode` AS `customer_postcode`,\n   `cs`.`phone` AS `customer_phone`,\n   `cs`.`address1` AS `customer_address1`,\n   `cs`.`address2` AS `customer_address2`,\n   `us`.`name` AS `staff_name`,\n   `ps`.`user_id` AS `user_id`,\n   `ps`.`status` AS `status`,\n   `ps`.`vendor_id` AS `vendor_id`\nFROM ((((((`cartitems` `ci` left join `products` `pd` on((`ci`.`product_id` = `pd`.`id`))) left join `catalogues` `cat` on((`pd`.`catalogue_id` = `cat`.`id`))) left join `pos` `ps` on((`ci`.`po_id` = `ps`.`id`))) left join `subcatalogues` `subcat` on((`pd`.`subcatalogue_id` = `subcat`.`id`))) left join `users` `us` on((`ps`.`user_id` = `us`.`id`))) left join `customers` `cs` on((`ps`.`customer_id` = `cs`.`id`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `ci`.`created_at` AS `date`,`ci`.`po_id` AS `po_id`,`ci`.`product_id` AS `product_id`,`cat`.`name` AS `catalogue`,`subcat`.`name` AS `subcatalogue`,`ps`.`paid_customer` AS `paid_customer`,`ps`.`paid_vendor` AS `paid_vendor`,`pd`.`product_code` AS `product_code`,`pd`.`postimage` AS `postimage`,`pd`.`thumbImage` AS `thumbimage`,`pd`.`name` AS `name_cn`,`pd`.`name_jp` AS `name_jp`,`pd`.`tablets` AS `tablets`,`pd`.`unit` AS `unit`,`pd`.`r_price` AS `r_price`,`pd`.`b_price` AS `b_price`,`pd`.`o_price` AS `o_price`,`ci`.`qty` AS `Qty`,`ci`.`total_r_price` AS `total_r_price`,`ci`.`total_b_price` AS `total_b_price`,`ci`.`total_o_price` AS `total_o_price`,`cs`.`name` AS `customer_name`,`cs`.`postcode` AS `customer_postcode`,`cs`.`phone` AS `customer_phone`,`cs`.`address1` AS `customer_address1`,`cs`.`address2` AS `customer_address2`,`us`.`name` AS `staff_name`,`ps`.`user_id` AS `user_id`,`ps`.`status` AS `status`,`ps`.`vendor_id` AS `vendor_id` from ((((((`misawa2020`.`cartitems` `ci` left join `misawa2020`.`products` `pd` on((`ci`.`product_id` = `pd`.`id`))) left join `misawa2020`.`catalogues` `cat` on((`pd`.`catalogue_id` = `cat`.`id`))) left join `misawa2020`.`pos` `ps` on((`ci`.`po_id` = `ps`.`id`))) left join `misawa2020`.`subcatalogues` `subcat` on((`pd`.`subcatalogue_id` = `subcat`.`id`))) left join `misawa2020`.`users` `us` on((`ps`.`user_id` = `us`.`id`))) left join `misawa2020`.`customers` `cs` on((`ps`.`customer_id` = `cs`.`id`)))
