# Generated by Django 2.2.2 on 2019-10-19 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('40df5dde-55bb-4f39-84ef-9c56aa7f8163'), null=True),
        ),
    ]
