# Generated by Django 2.2.2 on 2019-10-19 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20191019_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cb25171a-ca3e-4786-b828-47ec41be788b'), null=True),
        ),
    ]
