# Generated by Django 2.2.2 on 2019-10-19 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20191019_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ce4ed913-fa38-4c37-88e4-a1fffbc23cfa'), null=True),
        ),
    ]
