# Generated by Django 2.2.2 on 2019-10-21 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20191019_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5cf13d9c-3d79-47ed-928d-2f6a7574b8ea'), null=True),
        ),
    ]
