# Generated by Django 2.2.2 on 2019-10-22 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('50f8fe93-0623-463e-a10c-c19d3ccbfedb'), null=True),
        ),
    ]
