# Generated by Django 2.2.2 on 2019-10-21 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20191021_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3a73fe45-5b6d-4d0d-bddb-664f4dcbf4d5'), null=True),
        ),
    ]
