# Generated by Django 2.2.2 on 2019-10-22 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_auto_20191022_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('807e64cc-8038-4b11-80ea-463b9fd590c8'), null=True),
        ),
    ]
