# Generated by Django 2.2.2 on 2019-10-22 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_auto_20191022_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('827d69ed-70f9-4139-86ff-1d86e4e6f1ff'), null=True),
        ),
    ]
