# Generated by Django 2.2.2 on 2019-10-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_merge_20191022_1352'),
        ('useraccount', '0008_auto_20191022_2136'),
    ]

    operations = [
    ]
