# Generated by Django 2.2.2 on 2019-10-25 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20191022_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a983a3fb-ddf7-49a4-9981-5ae8d247f383'), null=True),
        ),
    ]
