# Generated by Django 2.2.2 on 2019-10-25 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_auto_20191025_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ec483630-7f21-4a8b-819b-2f018570e0e2'), null=True),
        ),
    ]
