# Generated by Django 2.2.2 on 2019-10-25 23:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_auto_20191025_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('981ecde4-93c4-4bf0-881e-afb853687a35'), null=True),
        ),
    ]
