# Generated by Django 2.2.2 on 2019-10-25 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_auto_20191025_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f79d71b6-972a-419e-923a-baa9ee35d95f'), null=True),
        ),
    ]
