# Generated by Django 2.2.2 on 2019-10-27 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_auto_20191025_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a65e3ba7-659c-439d-8494-a009311a7b83'), null=True),
        ),
    ]
