# Generated by Django 2.2.2 on 2019-11-11 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_auto_20191107_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('237ebf46-ed96-4eab-a729-9dac47801b76'), null=True),
        ),
    ]
