# Generated by Django 2.2.2 on 2019-11-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_auto_20191111_0949'),
        ('useraccount', '0014_merge_20191025_2328'),
    ]

    operations = [
    ]
