# Generated by Django 2.2.2 on 2019-11-18 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_auto_20191118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e1d4229d-6aa3-439b-a043-d878f7044a5f'), null=True),
        ),
    ]
