# Generated by Django 2.2.2 on 2019-11-18 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0020_auto_20191118_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b42007dc-0185-4c6d-9f3a-3ef41ca7b9a2'), null=True),
        ),
    ]
