# Generated by Django 2.2.2 on 2019-11-19 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0021_auto_20191118_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('14472116-ccd9-450f-a3ae-dd43ec868ae3'), null=True),
        ),
    ]
