# Generated by Django 2.2.2 on 2019-11-19 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0024_auto_20191119_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('87ad2ed9-7195-4e21-b0fe-9960dedb0418'), null=True),
        ),
    ]
