# Generated by Django 2.2.2 on 2019-11-20 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0026_auto_20191119_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('dafe0144-07e0-4203-996d-629dc8d02595'), null=True),
        ),
    ]
