# Generated by Django 2.2.2 on 2019-11-20 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0027_auto_20191120_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('06f05b32-b715-4fab-9713-62b09bf57757'), null=True),
        ),
    ]
