# Generated by Django 2.2.2 on 2019-11-20 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0028_auto_20191120_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('93f214fb-277b-48f9-aff2-d06a28970b6f'), null=True),
        ),
    ]
