# Generated by Django 2.2.2 on 2019-11-21 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0029_auto_20191120_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('56b22911-5098-45e4-ae15-78f350d4ee88'), null=True),
        ),
    ]
