# Generated by Django 2.2.2 on 2019-11-21 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0030_auto_20191121_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('dd2c3370-f452-47bb-9a20-8b458ab44490'), null=True),
        ),
    ]
