# Generated by Django 2.2.2 on 2019-11-21 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0031_auto_20191121_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d438f98d-74bc-4c9e-b253-96201917252f'), null=True),
        ),
    ]
