# Generated by Django 2.2.2 on 2019-11-21 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0032_auto_20191121_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f38236bd-08e7-4feb-8ac4-3ea79dfc6894'), null=True),
        ),
    ]
