# Generated by Django 2.2.2 on 2019-11-21 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0033_auto_20191121_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('44dc6582-64cc-4d2e-a282-07495631bcb8'), null=True),
        ),
    ]
