# Generated by Django 2.2.2 on 2019-11-21 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0034_auto_20191121_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e9ae62aa-e1b2-47fc-86ea-3efae3be4c20'), null=True),
        ),
    ]
