# Generated by Django 2.2.2 on 2019-11-21 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0036_auto_20191121_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('60be8ade-fd9c-47ec-b542-8c79375cc193'), null=True),
        ),
    ]
