# Generated by Django 2.2.2 on 2019-11-21 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0037_auto_20191121_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('98355f68-ddfb-4361-90c9-19d0f81fbfac'), null=True),
        ),
    ]
