# Generated by Django 2.2.2 on 2019-11-21 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0039_auto_20191121_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ab29aa9f-20d1-468a-89a9-dfef3db7c09b'), null=True),
        ),
    ]
