# Generated by Django 2.2.2 on 2019-11-22 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0040_auto_20191121_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('00b0ae36-c3c1-4325-ae1f-984cf4496ebd'), null=True),
        ),
    ]
