# Generated by Django 2.2.2 on 2019-11-22 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0041_auto_20191122_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('895b17a5-cf94-40c9-8257-cf0163fbc7a6'), null=True),
        ),
    ]
