# Generated by Django 2.2.2 on 2019-11-22 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0042_auto_20191122_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8d656313-d8c7-4fa4-a16b-2b63898d77f5'), null=True),
        ),
    ]
