# Generated by Django 2.2.2 on 2019-11-22 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0043_auto_20191122_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0830668a-389d-4b8b-b6c2-82223906bfec'), null=True),
        ),
    ]
