# Generated by Django 2.2.2 on 2019-11-22 15:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0044_auto_20191122_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('810ea5e6-5800-4247-9a45-39d9105be942'), null=True),
        ),
    ]
