# Generated by Django 2.2.2 on 2019-11-22 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0045_auto_20191122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e0c29d8a-4a55-41f2-bdd5-c9839cf0f7de'), null=True),
        ),
    ]
