# Generated by Django 2.2.2 on 2019-11-28 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0047_auto_20191124_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5fd082cd-d9ff-4889-b133-b1d0f581ca16'), null=True),
        ),
    ]
