# Generated by Django 2.2.2 on 2019-11-30 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0049_auto_20191128_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0133bea7-3be1-44d3-88b3-0e930cdb2ff8'), null=True),
        ),
    ]
