# Generated by Django 2.2.2 on 2019-11-30 17:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0050_auto_20191130_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('80e56e3f-600a-485a-9df6-f9acb7518eb2'), null=True),
        ),
    ]
