# Generated by Django 2.2.2 on 2019-11-30 18:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0051_auto_20191130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bf43cf62-da50-425d-98c4-d119d082abf5'), null=True),
        ),
    ]
