# Generated by Django 2.2.2 on 2019-12-08 18:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0052_auto_20191130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('49ffe066-672e-4149-9e1c-f3916ce20034'), null=True),
        ),
    ]
