# Generated by Django 2.2.2 on 2019-12-12 20:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0053_auto_20191208_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0eb0bbc8-959f-4690-83cc-8d4a4a526f69'), null=True),
        ),
    ]
