# Generated by Django 2.2.2 on 2019-12-12 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0054_auto_20191212_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c013a62e-2a50-4bea-87f5-cebce578302f'), null=True),
        ),
    ]
