# Generated by Django 2.2.2 on 2019-12-17 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0055_auto_20191212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8f9a19b4-aed4-4930-9590-a5cf0a61258b'), null=True),
        ),
    ]
