# Generated by Django 2.2.2 on 2019-12-17 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0056_auto_20191217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('dc00575a-e771-464d-a3eb-72c15ea6b01c'), null=True),
        ),
    ]
