# Generated by Django 2.2.2 on 2019-12-18 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0057_auto_20191217_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('df935d00-d000-44df-8faf-b2cbe5f67108'), null=True),
        ),
    ]
