# Generated by Django 2.2.2 on 2019-12-22 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0058_auto_20191218_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, default='jp', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a0ef2b20-9c81-4e4d-be0f-f9f84c5c9094'), null=True),
        ),
    ]
