# Generated by Django 2.2.2 on 2019-12-22 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0059_auto_20191222_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cd4ea06b-eaea-4845-9675-41c0d11436cf'), null=True),
        ),
    ]
