# Generated by Django 2.2.2 on 2019-12-22 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0060_auto_20191222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('285ed044-32d6-49ff-bec7-11828a66af0e'), null=True),
        ),
    ]
