# Generated by Django 2.2.2 on 2019-12-24 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0061_auto_20191222_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cd81f729-5347-4558-aee5-5f26767c8090'), null=True),
        ),
    ]
