# Generated by Django 2.2.2 on 2019-12-24 23:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0062_auto_20191224_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('71a32e93-8f20-4f7e-aeee-71f383219d91'), null=True),
        ),
    ]
