# Generated by Django 2.2.2 on 2019-12-24 23:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0063_auto_20191224_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c454594f-abaa-4835-8507-e17e9dc561e6'), null=True),
        ),
    ]
