# Generated by Django 2.2.2 on 2019-12-25 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0064_auto_20191224_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('e387ed6a-3cb3-43f0-ad40-d3ae7194ddce'), null=True),
        ),
    ]
