# Generated by Django 2.2.2 on 2019-12-28 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0065_auto_20191225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ac9778bb-0642-4570-8a45-15408202ae65'), null=True),
        ),
    ]
