# Generated by Django 2.2.2 on 2019-12-29 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0066_auto_20191228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c7d72517-7d31-4db8-8c6f-07b133ff18e0'), null=True),
        ),
    ]
