# Generated by Django 2.2.2 on 2020-01-08 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0067_auto_20191229_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('19eae15e-8a30-42b9-a7c2-deaab46d7367'), null=True),
        ),
    ]
