# Generated by Django 2.2.2 on 2020-01-08 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0068_auto_20200108_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a66f4644-8e33-4f6c-86b5-0d3b6aa3d803'), null=True),
        ),
    ]
