# Generated by Django 2.2.2 on 2020-01-08 18:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0069_auto_20200108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b84c55f2-62f8-4167-a420-d424de297dfa'), null=True),
        ),
    ]
