# Generated by Django 2.2.2 on 2019-10-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('b0140601-362e-4e5f-95cc-8139de52e883'), null=True)),
                ('name', models.CharField(blank=True, default='catalogue_name', max_length=128)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Catalogue',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('0593d5f2-ae55-4912-b71a-51d1a10d6da0'), null=True)),
                ('name', models.CharField(blank=True, default='catalogue_name', max_length=128)),
                ('purchase_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('open_price', models.IntegerField(default=0)),
                ('wanted', models.IntegerField(default=0)),
                ('main_product_id', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='WantedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('483953dc-1084-46bd-a4b4-f914272a65dd'), null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_products', to='lottery_shop.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wanted_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WantedProduct',
            },
        ),
        migrations.CreateModel(
            name='Subcatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('232e9d48-f669-4f49-8ae6-ed24e4dc8ee6'), null=True)),
                ('name', models.CharField(blank=True, default='subcatalogue_name', max_length=128)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogues', to='lottery_shop.Catalogue')),
            ],
            options={
                'verbose_name': 'Subatalogue',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lottery_shop.Subcatalogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
