# Generated by Django 2.2.2 on 2019-11-19 20:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('name', models.CharField(blank=True, default='catalogue_name', max_length=128)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Catalogue',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('name', models.CharField(blank=True, default='catalogue_name', max_length=128)),
                ('purchase_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('open_price', models.IntegerField(default=0)),
                ('wanted', models.IntegerField(default=0)),
                ('ranks', models.IntegerField(default=0)),
                ('main_product_id', models.IntegerField(blank=True, default=0, null=True)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('active', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Subcatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('name', models.CharField(blank=True, default='subcatalogue_name', max_length=128)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('catalogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogues', to='lottery_shop.Catalogue')),
            ],
            options={
                'verbose_name': 'Subatalogue',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'ProductImages',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lottery_shop.Subcatalogue'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Groupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('name', models.CharField(default='groupon name', max_length=1024)),
                ('description', models.CharField(blank=True, default='description of groupon', max_length=1024)),
                ('status', models.CharField(default='groupon status', max_length=20)),
                ('target', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('feedbackprice', models.IntegerField(default=0)),
                ('price_overflow', models.IntegerField(default=0)),
                ('feedbackprice_overflow', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupon', to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'Groupon',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField()),
                ('num', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('feedbackprice', models.IntegerField(default=0)),
                ('deposite_paycode', models.CharField(default='', max_length=20)),
                ('deposite_paid', models.BooleanField(default=False)),
                ('deposite_paid_at', models.DateTimeField(auto_now=True, verbose_name='deposite_paid_at')),
                ('order_paid', models.BooleanField(default=False)),
                ('order_paid_at', models.DateTimeField(auto_now=True, verbose_name='order_paid_at')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('groupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='lottery_shop.Groupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GrouponApplicant',
            },
        ),
    ]
