# Generated by Django 2.2.2 on 2019-11-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='brand', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='manufacturer', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='sku', max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, default='specs', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='catalogue_name', max_length=256),
        ),
    ]
