# Generated by Django 2.2.2 on 2019-10-12 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bc143865-1a32-4450-bbe3-003ca8574700'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('79991eec-9065-4972-9042-6b562bfb4c76'), null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7653c536-ca3a-43f0-98f8-c3b125c8a490'), null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('28e42f3f-d224-4026-8f52-5dd3eaaeec8c'), null=True),
        ),
    ]
