# Generated by Django 2.2.2 on 2019-11-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0002_auto_20191120_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='order_paid',
            new_name='orderpaid',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='order_paid_at',
            new_name='orderpaid_at',
        ),
    ]
