# Generated by Django 2.2.2 on 2019-10-12 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0002_auto_20191012_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('25a1236a-51b0-4373-8445-23cec6273ddd'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d98c39a0-5c0e-4ca7-806d-6450804f425e'), null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b845136a-f4ef-413a-bd1b-7f0648ed43c6'), null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('bc69ff05-a401-4c8b-951f-cdc21abd75fd'), null=True),
        ),
    ]
