# Generated by Django 2.2.2 on 2019-11-20 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0003_auto_20191120_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='groupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='lottery_shop.Groupon'),
        ),
    ]
