# Generated by Django 2.2.2 on 2019-10-12 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0003_auto_20191012_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f5cd347a-ad7d-4d53-9ce0-0b20f9552ce9'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b693cf9f-09ce-43e0-a0a2-7a546bdd4913'), null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('11fe3e39-f994-46fc-bf85-18984e433c0e'), null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c36fadfc-5b0c-4a82-b7ad-0ba15e86dc93'), null=True),
        ),
    ]
