# Generated by Django 2.2.2 on 2019-10-12 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0004_auto_20191012_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a915167b-d617-437a-a386-d9fc74661228'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ff55c097-eda1-4298-91cf-f7375d0c825b'), null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4ae5626a-408f-4588-9c52-9752f28e0b0f'), null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('1380bc94-271f-449e-9c8a-2e5aefe0f9a9'), null=True),
        ),
    ]
