# Generated by Django 2.2.2 on 2019-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0004_auto_20191120_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='delivery_no',
            field=models.CharField(default='delivery_no', max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='delivery_status',
            field=models.CharField(default='delivery status', max_length=20),
        ),
    ]
