# Generated by Django 2.2.2 on 2019-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0005_auto_20191121_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='imagetype',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Html', 'Html'), ('Others', 'Others')], default='Image', max_length=10),
        ),
    ]
