# Generated by Django 2.2.2 on 2019-10-12 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0005_auto_20191012_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4f76e7f7-f648-47ef-a1e5-281d3fbe24fc'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a324c808-451d-4086-a54b-b601ef3c620c'), null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('7949ca85-13be-4fd4-9934-6ee1212ba336'), null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cd94163c-ece3-45ec-ab70-0af37c158eff'), null=True),
        ),
    ]
