# Generated by Django 2.2.2 on 2019-11-21 20:58

from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0006_productimage_imagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('mediatype', models.CharField(choices=[('iframe', 'iframe'), ('video', 'video'), ('standard', 'standard'), ('Others', 'Others')], default='Image', max_length=10)),
                ('postimage', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('ajax_url', models.CharField(blank=True, default='ajax_url', max_length=256)),
                ('video_url', models.CharField(blank=True, default='video_url', max_length=256)),
                ('memo', models.CharField(blank=True, default='memo', max_length=256)),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('postimage', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('hiddel', models.CharField(blank=True, default='hidden', max_length=10)),
                ('jump_url', models.CharField(blank=True, default='jump_url', max_length=256)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleryimages', to='lottery_shop.Article')),
            ],
            options={
                'verbose_name': 'GalleryImage',
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
