# Generated by Django 2.2.2 on 2019-10-13 09:28

from django.db import migrations, models
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0006_auto_20191012_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='slug',
            field=models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='subcatalogue',
            name='slug',
            field=models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='wantedproduct',
            name='slug',
            field=models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True),
        ),
    ]
