# Generated by Django 2.2.2 on 2019-11-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0007_auto_20191121_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='hiddel',
            new_name='hidden',
        ),
    ]
