# Generated by Django 2.2.2 on 2019-10-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0007_auto_20191013_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ranks',
            field=models.IntegerField(default=0),
        ),
    ]
