# Generated by Django 2.2.2 on 2019-11-18 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery_shop', '0008_product_ranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('status', models.CharField(default='status', max_length=20)),
                ('num', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'GrouponApplicant',
            },
        ),
        migrations.CreateModel(
            name='Groupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('name', models.CharField(default='groupon name', max_length=1024)),
                ('description', models.CharField(blank=True, default='description of groupon', max_length=1024)),
                ('status', models.CharField(default='groupon status', max_length=20)),
                ('target', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('feedbackprice', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery_shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupon_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductGroupon',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('avatar', models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'ProductImages',
            },
        ),
        migrations.DeleteModel(
            name='WantedProduct',
        ),
        migrations.AddField(
            model_name='applicant',
            name='groupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lottery_shop.Groupon'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupon_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
