# Generated by Django 2.2.2 on 2019-11-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0008_auto_20191121_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='hidden',
            new_name='class_hidden',
        ),
    ]
