# Generated by Django 2.2.2 on 2019-11-21 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0009_auto_20191121_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='class_hidden',
            new_name='showme',
        ),
    ]
