# Generated by Django 2.2.2 on 2019-11-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0009_auto_20191118_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupon',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupon', to='lottery_shop.Product'),
        ),
    ]
