# Generated by Django 2.2.2 on 2019-11-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0010_auto_20191118_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupon',
            name='user',
        ),
    ]
