# Generated by Django 2.2.2 on 2019-11-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0010_auto_20191121_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='showme',
        ),
    ]
