# Generated by Django 2.2.2 on 2019-11-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0011_remove_galleryimage_showme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='jump_url',
        ),
    ]
