# Generated by Django 2.2.2 on 2019-11-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0012_remove_galleryimage_jump_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='memo',
            field=models.CharField(blank=True, default='memo', max_length=20),
        ),
    ]
