# Generated by Django 2.2.2 on 2019-11-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0013_galleryimage_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='postimage',
        ),
    ]
