# Generated by Django 2.2.2 on 2019-11-22 10:02

from django.db import migrations, models
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0014_remove_article_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postimage',
            field=models.ImageField(blank=True, default='new.jpg', null=True, upload_to=lottery_shop.models.get_image_path),
        ),
    ]
