# Generated by Django 2.2.2 on 2019-11-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0015_article_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='memo',
            field=models.CharField(blank=True, default='hidden', max_length=256),
        ),
    ]
