# Generated by Django 2.2.2 on 2019-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0016_auto_20191122_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, default='subtitle', max_length=256),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='product name', max_length=256),
        ),
    ]
