# Generated by Django 2.2.2 on 2019-12-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0018_auto_20191124_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='article',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='href',
            field=models.CharField(blank=True, default='href', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='mediatype',
            field=models.CharField(choices=[('iframe', 'iframe'), ('video', 'video'), ('standard', 'standard'), ('Others', 'Others')], default='Image', max_length=10),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='lottery_shop.Product'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=20),
        ),
    ]
