# Generated by Django 2.2.2 on 2019-12-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0019_auto_20191208_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=256),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='href',
            field=models.CharField(blank=True, default='href', max_length=256),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='memo',
            field=models.CharField(blank=True, default='memo', max_length=1024),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=256),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
