# Generated by Django 2.2.2 on 2019-12-12 20:26

from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0020_auto_20191212_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='snsURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('mediatype', models.CharField(choices=[('youtube', 'youtube'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram'), ('line', 'line'), ('wechat', 'wechat')], default='facebook', max_length=10)),
                ('description', models.CharField(blank=True, default='description', max_length=256)),
                ('href', models.CharField(blank=True, default='href', max_length=256)),
                ('memo', models.CharField(blank=True, default='memo', max_length=1024)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snsURLs', to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'snsURL',
            },
        ),
    ]
