# Generated by Django 2.2.2 on 2020-01-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lottery_shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery_shop', '0022_auto_20200108_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=lottery_shop.models.now_slug, null=True)),
                ('review', models.TextField(blank=True, default='specs', null=True)),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='created')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lottery_shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductReview',
            },
        ),
    ]
