# Generated by Django 2.2.2 on 2019-10-19 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('c8d96219-4d39-4b9a-9457-f493ececacb5'), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='rmb', max_length=3)),
                ('due_at', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 13, 19, 48, 82039))),
                ('send_notification', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=10)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_place_offer', 'Can place offer'), ('can_edit_offer', 'Can edit offer')),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('26825c46-9c7f-457b-91a1-d11d4816fae4'), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('from_currency', models.CharField(default='jpy', max_length=3)),
                ('to_currency', models.CharField(default='rmb', max_length=3)),
                ('due_at', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 13, 19, 48, 81029))),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=10)),
                ('privacy', models.CharField(default='public', max_length=10)),
                ('send_notification', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, default='...', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_place_order', 'Can place order'), ('can_edit_order', 'Can edit order')),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.UUID('85df58b8-910a-4b91-b731-d34c7dd9c66f'), null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mail_exchange.Offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mail_exchange.Order')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='mail_exchange.Order'),
        ),
    ]
