# Generated by Django 2.2.2 on 2019-10-21 10:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0002_auto_20191019_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuspoint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 10, 48, 53, 347594)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f0cc5a92-dfcb-48d3-9b93-3259b482706b'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 10, 48, 53, 346263)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('29fdc53e-8ff0-4cd3-9e66-f4202ec57c90'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('0c8427e5-63f2-4a2d-a1a0-be0cf8f06e60'), null=True),
        ),
    ]
