# Generated by Django 2.2.2 on 2019-10-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0005_merge_20191022_1352'),
        ('mail_exchange', '0006_auto_20191022_2136'),
    ]

    operations = [
    ]
