# Generated by Django 2.2.2 on 2019-10-25 21:44

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0006_auto_20191022_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 21, 44, 37, 765668)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a5be77a4-98cc-47cb-9cfa-3edf5519a3e0'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 21, 44, 37, 764712)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4d0c7f3a-ac6c-473e-b1b4-ee869b7abf0c'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c9569e15-0777-4ed9-ae29-ecec2e1ab47f'), null=True),
        ),
    ]
