# Generated by Django 2.2.2 on 2019-10-27 13:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0011_auto_20191025_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 13, 2, 42, 345967)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ebcfe6d3-912f-4ecb-8336-babc8ef0020d'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 13, 2, 42, 343376)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('71bc9c49-6179-4a4e-8ad0-d1dcdb50a5b3'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6434de06-5acc-4fe0-8a31-a98b29cbe7fa'), null=True),
        ),
    ]
