# Generated by Django 2.2.2 on 2019-11-18 21:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0016_merge_20191112_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 21, 15, 15, 291420)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('512e8252-cfff-4aca-bd66-ecc2546e4727'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 21, 15, 15, 288881)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ee0ceab3-bf10-4ae9-bd27-caa5acb5db58'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8e2bfa51-dc5e-443f-8ee1-e039fbfc8c41'), null=True),
        ),
    ]
