# Generated by Django 2.2.2 on 2019-11-22 15:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0042_auto_20191122_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 15, 5, 32, 108701)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3f768cd5-45a2-4075-81a4-21849130e710'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 15, 5, 32, 107726)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5cb4fc1b-658f-42aa-a2a3-d9aa98e5eb92'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a08f64df-6c65-42d5-a6a8-6d28c1a21b9a'), null=True),
        ),
    ]
