# Generated by Django 2.2.2 on 2019-11-28 22:58

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0045_auto_20191124_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate_alpha',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 22, 58, 29, 270172)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('155502d4-c952-469d-91c6-adbe52845324'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 22, 58, 29, 268991)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('588ddb5c-cdfd-490d-86b1-6d3650977b2d'), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6a593e81-e229-4871-8603-bf61b93bd931'), null=True),
        ),
    ]
