# Generated by Django 2.2.2 on 2019-11-30 17:50

import datetime
from django.db import migrations, models
import mail_exchange.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0047_auto_20191128_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 17, 50, 34, 295381)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('c4112c99-854e-4b74-b16c-04630981b0c2'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 17, 50, 34, 294264)),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=mail_exchange.models.uuid_time, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('18e8ddda-34a8-4d44-a7d4-15a6d0319ca2'), null=True),
        ),
    ]
