# Generated by Django 2.2.2 on 2019-11-30 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0049_auto_20191130_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 18, 27, 38, 368493)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d917cfd1-3ec3-4dfb-80a7-e05243ac97b8'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 18, 27, 38, 367415)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='mail_exchange.Offer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='mail_exchange.Order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5359d35b-c5f5-4b52-8ebd-b867c283fd6c'), null=True),
        ),
    ]
