# Generated by Django 2.2.2 on 2019-12-08 18:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0050_auto_20191130_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 18, 31, 6, 549094)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5e00a1bd-3c7b-428f-9ffa-722330d9e2a7'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 18, 31, 6, 547769)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d007bd21-f9bf-4c05-8ec7-ec0c24fa0113'), null=True),
        ),
    ]
