# Generated by Django 2.2.2 on 2019-12-18 23:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0055_auto_20191217_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 23, 11, 46, 998393)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('a77a3efc-365a-4515-a4ee-17c2ae8b8118'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 23, 11, 46, 997056)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('51dcbbd5-9b83-4c8a-abb3-f8c611658504'), null=True),
        ),
    ]
