# Generated by Django 2.2.2 on 2019-12-22 17:08

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0058_auto_20191222_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 17, 8, 40, 313888)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('d0b17afa-02fb-4424-ad74-61f9181c89dd'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 25, 17, 8, 40, 312443)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('68fd4fc6-ef17-48c9-9126-23ab2a3c3fb9'), null=True),
        ),
    ]
