# Generated by Django 2.2.2 on 2019-12-29 10:04

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0064_auto_20191228_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 10, 4, 52, 253363)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9f08fbac-6e0d-44ac-bc59-4d5ff4f78e87'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 10, 4, 52, 252225)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('45c7a6f1-7a3a-4cfd-95a3-235b48158905'), null=True),
        ),
    ]
