# Generated by Django 2.2.2 on 2020-01-08 12:15

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0065_auto_20191229_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 15, 24, 357729)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('4b019629-58c5-4a99-a227-1291b38bc222'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 15, 24, 356373)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5b5aa93f-59b2-4595-8093-eb02610ca95b'), null=True),
        ),
    ]
