# Generated by Django 2.2.2 on 2020-01-08 12:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0066_auto_20200108_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 48, 44, 485444)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('cb44986f-9e2d-4ed4-8687-51225deeb507'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 48, 44, 480273)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('36b8ec61-e67b-469c-a8ca-b6938c13558e'), null=True),
        ),
    ]
