# Generated by Django 2.2.2 on 2020-01-08 18:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_exchange', '0067_auto_20200108_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 18, 21, 33, 793961)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f124f43f-9997-46f9-9969-2591c2a25cd1'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 18, 21, 33, 792908)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b3fed543-6549-4d10-8164-f20e790ea6a5'), null=True),
        ),
    ]
