# Generated by Django 2.2.2 on 2019-11-19 22:13

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shoppingcart.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('street_address1', models.CharField(default='', max_length=255)),
                ('street_address2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=models.SET(shoppingcart.models.get_sentinel_user), related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='new', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coupontype', models.CharField(blank=True, default='amount', max_length=50, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.TextField(blank=True, default='', max_length=1024, null=True)),
                ('cartjson', django.contrib.postgres.fields.jsonb.JSONField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Address')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Cart')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoporders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('quantity', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='shoppingcart.Cart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery_shop.Product')),
            ],
            options={
                'verbose_name': 'CartItem',
                'ordering': ['slug'],
            },
        ),
    ]
