# Generated by Django 2.2.2 on 2019-11-20 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.CharField(blank=True, default='logistics', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, default='tracking_no', max_length=126, null=True),
        ),
    ]
