# Generated by Django 2.2.2 on 2019-10-12 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('ec03c5cb-a18d-460b-b438-43b0e6669a90'), null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b35b5440-3841-4540-a4c2-d2d8db4d8839'), null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9880b907-90ed-4332-9df8-ce035dd609e8'), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('b85e24e8-b879-400a-acbe-424fcf9e37d6'), null=True),
        ),
    ]
