# Generated by Django 2.2.2 on 2019-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_auto_20191120_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
