# Generated by Django 2.2.2 on 2019-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
