# Generated by Django 2.2.2 on 2019-10-12 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20191012_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('eafac3ef-7e8f-4a30-873d-30b51115c5f9'), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('8a07cedf-a09b-4842-a572-1121724ad8bc'), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('3823f6d9-8f5e-4908-93a9-8bd66a7c0402'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('5142cab3-b031-44f9-91ce-779c04e058cc'), null=True),
        ),
    ]
