# Generated by Django 2.2.2 on 2019-10-12 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_auto_20191012_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('9c79a2d4-1e2b-4ea0-b586-1b220161708c'), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('f05d14cf-febc-45ac-b798-1943f4904e9c'), null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('fc940a4a-aa3b-4954-806e-41a6281af3f9'), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.UUID('6ecd9e09-48c7-417c-8312-4e6a4d69f6d4'), null=True),
        ),
    ]
