# Generated by Django 2.2.2 on 2019-12-17 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20191217_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymethon',
            new_name='paymethod',
        ),
    ]
