# Generated by Django 2.2.2 on 2019-10-13 09:28

from django.db import migrations, models
import shoppingcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20191012_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True),
        ),
    ]
