# Generated by Django 2.2.2 on 2019-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_auto_20191013_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.TextField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
