# Generated by Django 2.2.2 on 2019-10-13 09:34

from django.db import migrations, models
import shoppingcart.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20191013_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=shoppingcart.models.now_slug, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.CharField(blank=True, default='new', max_length=50, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Coupon',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, default='nothing', max_length=50, null=True),
        ),
    ]
