# Generated by Django 2.2.2 on 2019-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0009_auto_20191013_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
