# Generated by Django 2.2.2 on 2019-10-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0011_auto_20191014_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartjson',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
