# Generated by Django 2.2.2 on 2019-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery_shop', '0007_auto_20191013_0928'),
        ('shoppingcart', '0012_auto_20191014_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(to='lottery_shop.Product'),
        ),
    ]
