# Generated by Django 2.2.2 on 2019-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0014_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(related_name='product', to='lottery_shop.Product'),
        ),
    ]
