# Generated by Django 2.2.2 on 2019-10-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0015_auto_20191014_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(related_name='cartitems', to='lottery_shop.Product'),
        ),
    ]
