# Generated by Django 2.2.2 on 2019-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0017_auto_20191014_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='new', max_length=50),
        ),
    ]
