# Generated by Django 2.2.2 on 2019-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0018_cartitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupontype',
            field=models.CharField(blank=True, default='amount', max_length=50, null=True),
        ),
    ]
