# Generated by Django 2.2.2 on 2019-10-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0019_coupon_coupontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
