# Generated by Django 2.2.2 on 2019-10-25 21:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0020_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartjson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='', null=True),
        ),
    ]
