# Generated by Django 2.2.2 on 2019-10-25 21:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0021_auto_20191025_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartjson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
