# Generated by Django 2.2.2 on 2019-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0022_auto_20191025_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartjson',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
